Make it work with GRPC
ysbaddaden/http2 pull request #15
Opened 2019-08-30 05:27 UTC by jgaskins

Since GRPC runs on top of HTTP/2, it seemed like a good way to do some real-world test cases.

I'm not super familiar with HTTP/2 so these tweaks were driven by error messages that came up when making GRPC calls using the official Google GRPC Ruby client to my Crystal GRPC server.

For context, here is the `call` method from my `HTTP2::Server::Handler` implementation:

```crystal
    def call(context : HTTP2::Server::Context)
      request, response = context.request, context.response

      compressed = request.body.read_bytes(UInt8) == 1 # ¯\_(ツ)_/¯
      length = request.body.read_bytes(UInt32, IO::ByteFormat::BigEndian)

      # TODO: Do some routing to dynamically map to the service and method
      buffer = CatalogHandler.new
        # .get_product(ProductRequest.from_protobuf(request.body))
        .get_products(pp ProductSearchQuery.from_protobuf(request.body))
        .to_protobuf

      response.headers["content-type"] = "application/grpc+proto"

      # Required for GRPC
      response.trailing_headers["grpc-status"] = "0"

      response.write_bytes 0_u8, IO::ByteFormat::BigEndian
      response.write_bytes buffer.bytesize, IO::ByteFormat::BigEndian

      buffer.rewind.to_s response
    end
```

I still get a few of these during requests but I can't tell if they're due to GRPC stuff or HTTP/2 stuff:

```
Unhandled exception in spawn: End of file reached (IO::EOFError)
  from /usr/local/Cellar/crystal/0.30.1/src/io.cr:513:27 in 'read_fully'
  from /usr/local/Cellar/crystal/0.30.1/src/io/byte_format.cr:131:3 in 'decode'
  from /usr/local/Cellar/crystal/0.30.1/src/int.cr:535:5 in 'from_io'
  from /usr/local/Cellar/crystal/0.30.1/src/io.cr:889:5 in 'read_bytes'
  from lib/http2/src/connection.cr:234:7 in 'read_frame_header'
  from lib/http2/src/connection.cr:164:7 in 'receive'
  from lib/http2/src/server.cr:177:24 in 'handle_http2_connection'
  from lib/http2/src/server.cr:151:13 in 'handle_http2_connection'
  from lib/http2/src/server.cr:93:20 in 'handle_socket'
  from lib/http2/src/server.cr:32:14 in '->'
  from /usr/local/Cellar/crystal/0.30.1/src/fiber.cr:255:3 in 'run'
  from /usr/local/Cellar/crystal/0.30.1/src/fiber.cr:47:34 in '->'
```

2019-08-30 09:31 UTC, ysbaddaden requested changes
They're called `trailers` in [RFC 7540](https://tools.ietf.org/html/rfc7540). Let's stick to HTTP naming.

2019-08-30 09:31 UTC, ysbaddaden commented on src/connection.cr
>          end
This isn't Ruby sending an Array, but `HTTP::Headers.each` passing an Array for the value. This should be rewritten to something like the following to avoid useless array allocations for each and every header:
```crystal
headers.each_key do |name|
  # ...

  if name == "te" && headers["te"] != "trailers"
    raise Error.protocol_error("MALFORMED #{name} header")
  end
end
```

Since `HTTP::Headers#each_key` doesn't seem to exist, it should be monkey patched (and/or maybe proposed to crystal as it would be a good addition):
```crystal
class HTTP::Headers
  def each_key
    @hash.each_key { |key| yield key }
  end
end
```

2019-08-30 09:31 UTC, ysbaddaden commented on src/server/response.cr
> +      def initialize(@stream : Stream, @headers : HTTP::Headers, @trailing_headers : HTTP::Headers)
Let's make trailers `nil` by default: we don't them in regular HTTP or HTTP/2 so it will spare an allocation.

Obviously response constructors should just pass `nil` too.

2019-08-30 12:38 UTC, jgaskins commented
> They're called `trailers` in RFC 7540. Let's stick to HTTP naming.

I mentioned something about the naming here in the commit message for cd629226d1de3f270ab55bf2fbae24422731be10. Glad to know we're on the same page there! :-)

2019-08-30 12:39 UTC, jgaskins commented on src/connection.cr
>          end
Oh this is interesting. For some reason I thought `HTTP::Headers` was just a type alias for `Hash(String, String)`.

2019-08-30 12:42 UTC, jgaskins commented on src/connection.cr
>          end
Just a point of order, though: wouldn't this only allocate the array for the `te` header due to short-circuiting in the condition?

2019-08-30 13:05 UTC, ysbaddaden commented on src/connection.cr
>          end
No, HTTP::Headers wrap a `Hash(String, Array(String) | String)`. HTTP headers are actually quite complex: they're case insensitive (so Content-Type == content-type == CONTENT-TYPE), and a single header may be repeated multiple cases, in which case we collect the values into an Array.

Hopefully iterating only keys and using the `[]` accessor should never allocate any array.

2025-10-28 12:46 UTC, ysbaddaden commented
Closing, `trailers` have since been added in `master`.

2025-10-28 12:46 UTC, closed without merging